// FOOD ENTRIES
export const SET_LOADING_FETCH_FOOD_ENTRIES = "SET_LOADING_FETCH_FOOD_ENTRIES";
export const FETCH_FOOD_ENTRIES_SUCCESS = "FETCH_FOOD_ENTRIES_SUCCESS";
export const FETCH_TODAYS_THRESHOLD_SUCCESS = "FETCH_TODAYS_THRESHOLD_SUCCESS";
export const FETCH_DAILY_THRESHOLDS_SUCCESS = "FETCH_DAILY_THRESHOLDS_SUCCESS";
export const SET_LOADING_FETCH_DAILY_THRESHOLDS = "SET_LOADING_FETCH_DAILY_THRESHOLDS";
export const SET_FOOD_ENTRY_DIALOG_LOADING = "SET_FOOD_ENTRY_DIALOG_LOADING";
export const DELETE_FOOD_ENTRY_SUCCESS = "DELETE_FOOD_ENTRY_SUCCESS";
export const CREATE_FOOD_ENTRY_SUCCESS = "CREATE_FOOD_ENTRY_SUCCESS";
export const UPDATE_FOOD_ENTRY_SUCCESS = "UPDATE_FOOD_ENTRY_SUCCESS";
export const SET_AUTOCOMPLETE_LOADING = "SET_AUTOCOMPLETE_LOADING";
export const FETCH_AUTOCOMPLETE_SUCCESS = "FETCH_AUTOCOMPLETE_SUCCESS";
export const FETCH_PIE_CHART_REPORT_SUCCESS = "FETCH_PIE_CHART_REPORT_SUCCESS";
export const FETCH_BAR_CHART_REPORT_SUCCESS = "FETCH_BAR_CHART_REPORT_SUCCESS";

// AUTH
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
